name = "CliffordBFS"
uuid = "4f3639b9-d846-4c20-bf8d-1487338b1c84"
authors = ["Ben Criger <ben.criger@quantinuum.com>"]
version = "0.1.0"

[deps]
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
